### PR TITLE
perf: Compile json validation schema at init instead of in the first call

### PR DESCRIPTION
**Pull request by organom**
When using the default JsonSchemaValidator to validate incoming POST and PUT calls, it was noticed that the first call would take longer than the subsequent ones (even with lambda provisioned concurrency).

This happens because the AJV library compiles the schema on the first validate if not compiled before.

**Description of changes:**
`COMPILE_SCHEMA` environment variable is added that when set to a value of `true`, compiles the Schema on the constructor.

Running the tests can easily prove the behavior:

- COMPILE_SCHEMA not set or different than `true`

Screenshot 2021-11-26 at 15 20 41

- COMPILE_SCHEMA set to `true`

Screenshot 2021-11-26 at 15 20 26

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by Bingjiling** [comment]
Hi @organom , 

Thanks for diving deep into this cold start behavior and contributing back to FWoA! 

I like the approach taken here. I don't think the environment variable `COMPILE_SCHEMA` is needed though, as it is improving performance without bringing side effect. Another nit-pick, could you please use `perf:` prefix for the commit message? (We have an automatic workflow to create a release pr if `feat:` prefix is used)

Thanks,
Yanyu

**Review by Bingjiling — CHANGES_REQUESTED** [review]
Please remove environment variable `COMPILE_SCHEMA` and use `perf:` for commit message prefix.

**Comment by organom** [comment]
@Bingjiling Thank you for the input and sorry for the delay on making the changes. They are now done as requested :)

**Review by Bingjiling — APPROVED** [review]
LGTM! Thanks again for your contribution 👍  Could you please update the branch to be up to date with mainline?

**Pull request merged**
